cafe_ordering_system/config/routes.rb
Rails.application.routes.draw do
  root "waiter_login#index"

  resources :chefs
  resources :waiters
  resources :items
  resources :order_items

  get "chef_login", to: "chef_login#index"
  post "chef_sign_in", to: "chef_login#sign_in"
  post "chef_sign_out", to: "chef_login#sign_out"
  get "waiter_login", to: "waiter_login#index"
  post "waiter_sign_in", to: "waiter_login#sign_in"
  post "waiter_sign_out", to: "waiter_login#sign_out"
  get "graph", to: "chefs#graph"

  get "chef_forget_password", to: "chef_password_resets#index"
  post "chef_forget_password", to: "chef_password_resets#create"
  get "chef_password_reset_edit", to: "chef_password_resets#edit"
  patch "chef_password_reset_edit", to: "chef_password_resets#update"

  get "waiter_forget_password", to: "waiter_password_reset#index"
  post "waiter_forget_password", to: "waiter_password_reset#create"
  get "waiter_password_reset_edit", to: "waiter_password_reset#edit"
  patch "waiter_password_reset_edit", to: "waiter_password_reset#update"

  get "password", to: "chefs#change_password"
  post "password", to: "chefs#update_password"

  get "waiter_password", to: "waiters#waiter_change_password"
  post "waiter_password", to: "waiters#waiter_update_password"

  #waiter order process
  post "select", to: "waiters#select_item"
  post "cancel", to: "waiters#cancel_item"
  post "confirm", to: "waiters#confirm_order"
  get "orders", to: "waiters#get_orders"
  get "order", to: "waiters#show_order"
  post "pick_order", to: "waiters#pick_order"

  #chef order process
  post "processing", to: "order_items#processing_item"
  post "finished", to: "order_items#finish"
end

cafe_ordering_system/app/models/chef.rb
class Chef < ApplicationRecord
  has_secure_password

  validates :name, presence: true, length: {maximum: 50}
  validates :email, presence: true, length: {maximum: 30}
  validates :password, presence: true, length: {in: 6..20}, on: :create
  validates :password, confirmation: true, on: :update
  validates :phone, presence: true, length: {in: 9..11}
  validates :address, presence: true, length: {maximum: 250}
  validates :birthday, presence: true
end

cafe_ordering_system/app/controllers/chefs_controller.rb
class ChefsController < ApplicationController
  before_action :chef_authorized, only: [:update, :show, :edit, :update_password]
  before_action :authorized, only: [:graph]
  def new
    @chef = Chef.new
  end

  def create
    @chef = Chef.new(chef_params)
    @is_chef_create = ChefService.create_chef(@chef)

    # check new chef is create or not
    if @is_chef_create
      redirect_to chef_login_path
    else
      render :new
    end
  end

  #update chef profile
  def update
    @chef = ChefService.get_chef_by_id(params[:id])
    @is_chef_update = ChefService.update_chef(@chef, chef_params)
    if @is_chef_update
      redirect_to chef_path(id: session[:chef_id])
    else
      render :edit
    end
  end

  #show chef profile
  def show
    @chef = ChefService.get_chef_by_id(params[:id])
  end

  #edit chef profile
  def edit
    @chef = ChefService.get_chef_by_id(params[:id])
  end

  #change password
  def update_password
    if params[:current_password].blank? || params[:password].blank? || params[:confirmation_password].blank?
      if params[:current_password].blank?
        @current = Messages::CURRENT_PASSWORD_REQUIRED
      end
      if params[:password].blank?
        @new = Messages::NEW_PASSWORD_REQUIRED
      end
      if params[:confirmation_password].blank?
        @confirm = Messages::CONFIRM_PASSWORD_REQUIRED
      end
      render :change_password
    else
      @chef = ChefService.get_chef_by_id(session[:chef_id])
      if @chef.authenticate(params[:current_password])
        if params[:password] != params[:confirmation_password]
          @confirm = Messages::CONFIRM_PASSWORD_VALIDATION
          render :change_password
        else
          @is_update_password = ChefService.update_password(@chef, params[:password])
          if @is_update_password
            redirect_to chef_path(id: session[:chef_id]), alert: Messages::PASSWORD_CHANGE_SUCCESS
          end
        end
      else
        @current = Messages::CURRENT_PASSWORD_VALIDATION
        render :change_password
      end
    end
  end

  def graph
    @start_date = Date.today - 7
    @end_date = Date.today - 1

    if params.has_key?(:graph_date)
      @start_date = params[:graph_date]
      @end_date = params[:graph_date].to_date + 6
    end

    @orders = OrderItemService.order_amount(@start_date, @end_date)
    @graph_data = {}

    @orders.each do |order|
      @graph_data[order.item_name] = order.total
    end
  end

  private

  def chef_params
    params.require(:chef).permit(:name, :email, :password, :phone, :birthday, :address)
  end
end

cafe_ordering_system/app/helpers/chefs_helper.rb
module ChefsHelper
end

cafe_ordering_system/app/views/chefs/change_password.html.erb
<div class="outer-container">
  <div class="container">
    <h2>Chef Password Change</h2>
    <%= form_with url: password_path, class: "login-form", method: :post do |f| %>
      <div class="mb-20">
        <%= f.password_field :current_password, class: "text-box", placeholder: "Enter Current Password" %>
        <% if @current %>
        <span class="error"><%= @current %></span>
        <% end %>
      </div>
      <div class="mb-20">
        <%= f.password_field :password, class: "text-box", placeholder: "Enter New Password" %>
        <% if @new %>
        <span class="error"><%= @new %></span>
        <% end %>
      </div>
      <div class="mb-20">
        <%= f.password_field :confirmation_password, class: "text-box", placeholder: "Confirm Your Password" %>
        <% if @confirm %>
        <span class="error"><%= @confirm %></span>
        <% end %>
      </div>
      <div class="submit">
        <%= f.submit "Update", class: "submit-btn" %>
        <%= link_to "Go Back", chef_path(id: session[:chef_id]), class: "cancel-btn" %>
      </div>
    <% end %>
  </div>
</div>

cafe_ordering_system/app/views/chefs/chef_profile.html.erb
<div class="outer-container">

  <div class="nav">
    <a>
      <h1 class="ttl-logo">SCM Cafe</h1>
    </a>
    <ul>
      <li><%= link_to "Order Lists", chefs_path, class: "link" %></li>
      <li><%= link_to "Item Lists", items_path, class: "link" %></li>
      <li><%= link_to "Profile", chef_profile_path, class: "link is-active" %></li>
      <li>Graph</li>
      <li><%= link_to "Log Out", chef_sign_out_path, class: "link", method: :post %></li>
    </ul>
  </div>
  
  <div class="container">
    <h2  class="mb-20">Chef Profile</h2>
    <div class="login-photo">
      <%= image_tag ("login_icons/img_chef_login.jpg"), class: "logo", alt: "sign up logo" %>
    </div>

    <ul class="column">
      <div class="left">
        <li class="mb-20">Name:</li>
        <li class="mb-20">Email:</li>
        <li class="mb-20">Phone:</li>
        <li class="mb-20">Address:</li>
        <li class="mb-20">Birthday:</li>
      </div>

      <div class="right">
        <li class="mb-20"><%= @chef.name %></li>
        <li class="mb-20"><%= @chef.email %></li>
        <li class="mb-20"><%= @chef.phone %></li>
        <li class="mb-20"><%= @chef.address %></li>
        <li class="mb-20"><%= @chef.birthday %></li>
      </div>
    </ul>

    <div class="profile-password">
      <div class="mb-10">
        <%= link_to "Edit Profile", edit_profile_path %><br>
      </div>
      <%= link_to "Change Password", password_path %>
    </div>

  </div>
</div>

cafe_ordering_system/app/views/chefs/edit.html.erb
<div class="outer-container">
  <div class="container">
    <div class="login-photo">
      <%= image_tag ("login_icons/img_chef_login.jpg"), class: "logo", alt: "sign up logo" %>
    </div>
    <h2>Update Profile</h2>
    <%= form_with model: @chef, class: "login-form" do |f| %>
      <div class="mb-20">
        <%= f.text_field :name, class: "text-box", placeholder: "Enter Name" %>
        <% @chef.errors.full_messages_for(:name).each do |message| %>
        <div class="text-danger"><%= message %></div>
        <% end %>
      </div>
      <div class="mb-20">
        <%= f.email_field :email, class: "text-box", placeholder: "Enter Email" %>
        <% @chef.errors.full_messages_for(:email).each do |message| %>
        <div class="text-danger"><%= message %></div>
        <% end %>
      </div>
      <div class="mb-20">
        <%= f.text_field :phone, class: "text-box", placeholder: "Enter Phone" %>
        <% @chef.errors.full_messages_for(:phone).each do |message| %>
        <div class="text-danger"><%= message %></div>
        <% end %>
      </div>
      <div class="mb-20">
        <%= f.text_field :birthday, onfocus: "(this.type='date')", class: "text-box", placeholder: "Enter Birthday" %>
        <% @chef.errors.full_messages_for(:birthday).each do |message| %>
        <div class="text-danger"><%= message %></div>
        <% end %>
      </div>
      <div class="mb-20">
        <%= f.text_area :address, class: "text-box", placeholder: "Enter Address" %>
        <% @chef.errors.full_messages_for(:address).each do |message| %>
        <div class="text-danger"><%= message %></div>
        <% end %>
      </div>
      <div class="submit">
        <%= f.submit "Update", class: "submit-btn" %>
        <%= link_to "Go Back", chef_path(id: session[:chef_id]), class: "cancel-btn" %>
      </div>
    <% end %>
  </div>
</div>

cafe_ordering_system/app/views/chefs/edit_profile.html.erb
<div class="outer-container">

  <div class="nav">
    <a>
      <h1 class="ttl-logo">SCM Cafe</h1>
    </a>
    <ul>
      <li><%= link_to "Order Lists", chefs_path, class: "link" %></li>
      <li>Item Lists</li>
      <li><%= link_to "Profile", chef_profile_path, class: "link is-active" %></li>
      <li>Graph</li>
      <li><%= link_to "Log Out", chef_sign_out_path, class: "link", method: :post %></li>
    </ul>
  </div>

  <div class="container">
    <div class="login-photo">
      <%= image_tag ("login_icons/img_chef_login.jpg"), class: "logo", alt: "sign up logo" %>
    </div>

    <h2>Update Profile</h2>
    <%= form_with model: @chef, class: "login-form" do |f| %>

      <div class="mb-20">
        <%= f.text_field :name, class: "text-box", placeholder: "Enter Name" %>
        <% @chef.errors.full_messages_for(:name).each do |message| %>
          <div class="text-danger"><%= message %></div>
        <% end %>
      </div>

      <div class="mb-20">
        <%= f.email_field :email, class: "text-box", placeholder: "Enter Email" %>
        <% @chef.errors.full_messages_for(:email).each do |message| %>
          <div class="text-danger"><%= message %></div>
        <% end %>
      </div>

      <div class="mb-20">
        <%= f.text_field :phone, class: "text-box", placeholder: "Enter Phone" %>
        <% @chef.errors.full_messages_for(:phone).each do |message| %>
          <div class="text-danger"><%= message %></div>
        <% end %>
      </div>

      <div class="mb-20">
        <%= f.text_field :birthday, onfocus: "(this.type='date')", class: "text-box", placeholder: "Enter Birthday" %>
        <% @chef.errors.full_messages_for(:birthday).each do |message| %>
          <div class="text-danger"><%= message %></div>
        <% end %>
      </div>

      <div class="mb-20">
        <%= f.text_area :address, class: "text-box", placeholder: "Enter Address" %>
        <% @chef.errors.full_messages_for(:address).each do |message| %>
          <div class="text-danger"><%= message %></div>
        <% end %>
      </div>

      <div class="submit">
        <%= f.submit "Update", class: "submit-btn" %>
        <%= link_to "Go Back", chef_profile_path, class: "cancel-btn" %>
      </div>

    <% end %>
    
  </div>
</div>

cafe_ordering_system/app/views/chefs/graph.html.erb
<div class="graph-container">
  <h1 class="graph-ttl">Weekly Best Selling Items' Graph</h1>
  <%= form_with url: graph_path, class: "graph-form mb-20", method: :get do |f| %>
    <div class="mb-20">
      <%= f.text_field :graph_date, onfocus: "(this.type='date')", max: Date.today - 7, class: "text-box", placeholder: "Choose a start date" %>
    </div>
    <div class="graph-submit">
      <%= f.submit "Show Data", class: "submit-btn" %>
    </div>
  <% end %>
  <div class="chart-container">
    <%= column_chart @graph_data, width: "100%", xtitle: "Items", ytitle: "Quantity", loading: "Loading...", empty: "No data", colors: ["#f70a16", "#35fc03", "#f7d70a", "#82817c", "#1a45f0", "#f28d11", "#6b1fde"] %>
    <p class="graph-content">Top 7 best selling items from "<%= @start_date %>" to "<%= @end_date %>"</p> 
  </div>
</div>

cafe_ordering_system/app/views/chefs/new.html.erb
<div class="container">
  <div class="login-photo">
    <%= image_tag ('login_icons/img_chef_login.jpg'), class: "logo", alt: 'sign up logo' %>
  </div>
  <h2>Chef Sign Up</h2>
  <%= render "common/sign_up_form", user: @chef %>
</div>

cafe_ordering_system/app/views/chefs/show.html.erb
<div class="outer-container">
  <div class="container">
    <h2 class="mb-20">Chef Profile</h2>
    <div class="login-photo">
      <%= image_tag ("login_icons/img_chef_login.jpg"), class: "logo", alt: "sign up logo" %>
    </div>
   <div class="column mb-20">
      <p class="left">Name:</p>
      <span class="right"><%= @chef.name %></span>
    </div>

    <div class="column mb-20">
      <p class="left">Email:</p>
      <span class="right"><%= @chef.email %></span>
    </div>

    <div class="column mb-20">
      <p class="left">Phone:</p>
      <span class="right"><%= @chef.phone %></span>
    </div>
    <div class="column mb-20">
      <p class="left">Address:</p>
      <span class="right"><%= @chef.address %></span>
    </div>
    <div class="column mb-20">
      <p class="left">Birthday:</p>
      <span class="right"><%= @chef.birthday %></span>
    </div>
    <div class="profile-password">
      <div class="mb-10">
        <%= link_to "Edit Profile", edit_chef_path(session[:chef_id]) %><br>
      </div>
      <%= link_to "Change Password", password_path %>
    </div>
  </div>
</div>